name: 构建并部署 Jekyll
on:
  push:
    branches:
      - main  # 默认分支名称

jobs:
  jekyll:
    runs-on: ubuntu-latest  # 运行在最新版本 Ubuntu 上
    steps:
      - name: 检出仓库
        uses: actions/checkout@v4.1.0  # 使用 GitHub Action 来检出您的仓库
        
      - name: 设置 Ruby
        uses: ruby/setup-ruby@v1  # 设置 Ruby 环境
        with:
          ruby-version: 3.1.3  #  Ruby 版本

      - name: 使用 Jekyll 构建站点
        run: |
          bundle install  # 安装依赖
          bundle exec jekyll build  # 使用 Jekyll 构建站点

      - name: 部署到 GitHub Pages
        uses: peaceiris/actions-gh-pages@v3  # 使用 GitHub Action 来部署到 GitHub Pages
        with:
          github_token: ${{ secrets.CUSTOM_PLUGINS }}  # 使用 GitHub Token 来获得权限
          publish_dir: ./_site  # 部署 _site 目录
